"""add agents sessions events

Revision ID: 362fddd0d613
Revises: 2e1172910ad3
Create Date: 2026-07-04 17:17:45.374577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362fddd0d613'
down_revision: Union[str, Sequence[str], None] = '2e1172910ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('vapi_assistant_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_vapi_assistant_id'), 'agents', ['vapi_assistant_id'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_agents_vapi_assistant_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
