"""add evidences

Revision ID: 89465196cf36
Revises: 362fddd0d613
Create Date: 2026-07-05 11:31:36.753027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89465196cf36'
down_revision: Union[str, Sequence[str], None] = '362fddd0d613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidences',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('criterion', sa.String(), nullable=False),
    sa.Column('conclusion', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('source_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidences_session_id'), 'evidences', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidences_session_id'), table_name='evidences')
    op.drop_table('evidences')
    # ### end Alembic commands ###
